[pytest]
markers =
    smoke: Дымовые тесты для критического функционала
    regression: Полный набор регрессионных тестов
    slow: Медленные тесты (например, с доступом к сети)
    profile: Тесты для пользовательского профиля
